version: '3.8'
services:
  sql:
    image: 'postgres:14'
    networks:
      - webproxy
    env_file:
      - .env
    ports:
      - 5432:5432
  api:
    build:
      context: '..'
      dockerfile: 'Dockerfile'
    container_name: holdim_admin_api
    networks:
      - webproxy
    env_file: .env
    ports:
      - '8080:8080'
    depends_on:
      - sql
networks:
  webproxy:
    driver: bridge
